Add the nearest-projection OpenFOAM example
precice/precice.github.io pull request #36
Opened 2021-03-11 21:22 UTC by DavidSCN

Hopefully added it in the right way. Related to precice/tutorials#159.

2021-03-12 13:23 UTC, MakisH requested changes
The sidebar part is fine, but we still need to add this in the project config: https://github.com/precice/precice.github.io/blob/master/_config.yml#L184

Incidentally, we don't have documentation about this at the moment. I opened an issue for now https://github.com/precice/precice.github.io/issues/37

2021-03-12 14:06 UTC, DavidSCN commented
Done :ok_hand:

2021-03-17 11:02 UTC, MakisH approved these changes

2021-03-17 11:08 UTC, DavidSCN commented
Waiting with the merge here until we merge precice/tutorials#149. Otherwise the page will be not found since it was not part of the initial template.

2021-03-23 06:56 UTC, merged